/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  BudgetProgramsApi,
  BudgetsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { BrexBudgetsCustom } from "./client-custom";

export class BrexBudgets extends BrexBudgetsCustom {
  readonly budgetPrograms: BudgetProgramsApi;
  readonly budgets: BudgetsApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.budgetPrograms = new BudgetProgramsApi(configuration);
    this.budgets = new BudgetsApi(configuration);
  }

}
