/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';

/**
 * 
 * @export
 * @interface BudgetLimit
 */
export interface BudgetLimit {
    /**
     * The amount of money, in the smallest denomination of the currency indicated by currency. For example, when currency is USD, amount is in cents.
     * @type {number}
     * @memberof BudgetLimit
     */
    'amount'?: number;
    /**
     * The type of currency, in ISO 4217 format. Default to USD if not specified
     * @type {string}
     * @memberof BudgetLimit
     */
    'currency'?: string | null;
}

