/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BudgetCurrentPeriodBalance } from './budget-current-period-balance';
import { BudgetLimit } from './budget-limit';
import { BudgetStatus } from './budget-status';
import { LimitType } from './limit-type';
import { PeriodType } from './period-type';
import { SpendType } from './spend-type';

/**
 * 
 * @export
 * @interface Budget
 */
export interface Budget {
    /**
     *  Description of what the Budget is used for. 
     * @type {string}
     * @memberof Budget
     */
    'description'?: string | null;
    /**
     *  Unique ID for the Budget. 
     * @type {string}
     * @memberof Budget
     */
    'budget_id'?: string;
    /**
     *  The Brex account this Budget belongs to. 
     * @type {string}
     * @memberof Budget
     */
    'account_id'?: string;
    /**
     *  The ID of the user who originally created this budget. 
     * @type {string}
     * @memberof Budget
     */
    'creator_user_id'?: string | null;
    /**
     *  Name for the Budget. 
     * @type {string}
     * @memberof Budget
     */
    'name'?: string;
    /**
     *  ID of parent Budget. 
     * @type {string}
     * @memberof Budget
     */
    'parent_budget_id'?: string | null;
    /**
     *  User IDs of the owners of the Budget. 
     * @type {Array<string>}
     * @memberof Budget
     */
    'owner_user_ids'?: Array<string>;
    /**
     *  User IDs of the members of the Budget. 
     * @type {Array<string>}
     * @memberof Budget
     */
    'member_user_ids'?: Array<string>;
    /**
     *  Period type of the Budget e.g. MONTHLY. 
     * @type {PeriodType}
     * @memberof Budget
     */
    'period_type': PeriodType;
    /**
     *  The UTC date when the Budget should start counting. 
     * @type {string}
     * @memberof Budget
     */
    'start_date'?: string | null;
    /**
     *  The UTC date when the Budget should stop counting. 
     * @type {string}
     * @memberof Budget
     */
    'end_date'?: string | null;
    /**
     * 
     * @type {BudgetLimit}
     * @memberof Budget
     */
    'limit'?: BudgetLimit;
    /**
     *  Status of the Budget e.g. APPROVED. 
     * @type {BudgetStatus}
     * @memberof Budget
     */
    'budget_status': BudgetStatus;
    /**
     * 
     * @type {LimitType}
     * @memberof Budget
     */
    'limit_type'?: LimitType;
    /**
     *  Whether this Budget only can be spent from by cards provisioned by this Budget.  
     * @type {SpendType}
     * @memberof Budget
     */
    'spend_type': SpendType;
    /**
     * 
     * @type {BudgetCurrentPeriodBalance}
     * @memberof Budget
     */
    'current_period_balance'?: BudgetCurrentPeriodBalance;
}

