/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BudgetLimit } from './budget-limit';
import { BudgetPeriodBalance } from './budget-period-balance';

/**
 * 
 * @export
 * @interface BudgetCurrentPeriodBalance
 */
export interface BudgetCurrentPeriodBalance {
    /**
     * 
     * @type {string}
     * @memberof BudgetCurrentPeriodBalance
     */
    'start_date'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetCurrentPeriodBalance
     */
    'end_date'?: string | null;
    /**
     * 
     * @type {BudgetLimit}
     * @memberof BudgetCurrentPeriodBalance
     */
    'balance'?: BudgetLimit;
}

