/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BudgetLimit } from './budget-limit';

/**
 *  Current Budget period balance. 
 * @export
 * @interface BudgetPeriodBalance
 */
export interface BudgetPeriodBalance {
    /**
     * 
     * @type {string}
     * @memberof BudgetPeriodBalance
     */
    'start_date'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetPeriodBalance
     */
    'end_date'?: string | null;
    /**
     * 
     * @type {BudgetLimit}
     * @memberof BudgetPeriodBalance
     */
    'balance'?: BudgetLimit;
}

