/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @enum {string}
 */
export type BudgetProgramStatus = 'BUDGET_PROGRAM_STATUS_ACTIVE' | 'BUDGET_PROGRAM_STATUS_INACTIVE' | 'BUDGET_PROGRAM_STATUS_DELETED'

