/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 *  Determines if budget members are allowed to view the budget limit. 
 * @export
 * @enum {string}
 */
export type BudgetLimitVisibilityType = 'SHARED' | 'PRIVATE'

