/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeFilter } from './employee-filter';
import { EmploymentStatus } from './employment-status';
import { EmploymentType } from './employment-type';

/**
 * 
 * @export
 * @interface CreateBudgetProgramRequestEmployeeFilter
 */
export interface CreateBudgetProgramRequestEmployeeFilter {
    /**
     * 
     * @type {EmploymentStatus}
     * @memberof CreateBudgetProgramRequestEmployeeFilter
     */
    'employment_status'?: EmploymentStatus;
    /**
     * 
     * @type {EmploymentType}
     * @memberof CreateBudgetProgramRequestEmployeeFilter
     */
    'employment_type'?: EmploymentType;
}

