/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateBudgetBlueprintRequest } from './create-budget-blueprint-request';
import { CreateBudgetProgramRequestEmployeeFilter } from './create-budget-program-request-employee-filter';

/**
 *  Budget Program used to create budgets for eligible users. 
 * @export
 * @interface CreateBudgetProgramRequest
 */
export interface CreateBudgetProgramRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateBudgetProgramRequest
     */
    'description'?: string | null;
    /**
     *  IDs for existing budgets associated with this Budget Program. 
     * @type {Array<string>}
     * @memberof CreateBudgetProgramRequest
     */
    'existing_budget_ids'?: Array<string> | null;
    /**
     * 
     * @type {Array<CreateBudgetBlueprintRequest>}
     * @memberof CreateBudgetProgramRequest
     */
    'budget_blueprints': Array<CreateBudgetBlueprintRequest>;
    /**
     * 
     * @type {CreateBudgetProgramRequestEmployeeFilter}
     * @memberof CreateBudgetProgramRequest
     */
    'employee_filter'?: CreateBudgetProgramRequestEmployeeFilter;
    /**
     * 
     * @type {string}
     * @memberof CreateBudgetProgramRequest
     */
    'name': string;
}

