/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 *  What kind of employment the employee has. 
 * @export
 * @enum {string}
 */
export type EmploymentType = 'EMPLOYMENT_TYPE_FULL_TIME' | 'EMPLOYMENT_TYPE_PART_TIME' | 'EMPLOYMENT_TYPE_CONTRACTOR' | 'EMPLOYMENT_TYPE_INTERN' | 'EMPLOYMENT_TYPE_FREELANCE'

