/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmploymentStatus } from './employment-status';
import { EmploymentType } from './employment-type';

/**
 *  A filter used to determine if a user adheres to a Budget Program. 
 * @export
 * @interface EmployeeFilter
 */
export interface EmployeeFilter {
    /**
     * 
     * @type {EmploymentStatus}
     * @memberof EmployeeFilter
     */
    'employment_status'?: EmploymentStatus;
    /**
     * 
     * @type {EmploymentType}
     * @memberof EmployeeFilter
     */
    'employment_type'?: EmploymentType;
}

