/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Budget } from './budget';

/**
 * 
 * @export
 * @interface PageBudget
 */
export interface PageBudget {
    /**
     * 
     * @type {string}
     * @memberof PageBudget
     */
    'next_cursor'?: string | null;
    /**
     * 
     * @type {Array<Budget>}
     * @memberof PageBudget
     */
    'items': Array<Budget>;
}

