/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateBudgetProgramRequestEmployeeFilter } from './create-budget-program-request-employee-filter';
import { UpdateBudgetBlueprintRequest } from './update-budget-blueprint-request';

/**
 *  Budget Program used to create budgets for eligible users. 
 * @export
 * @interface UpdateBudgetProgramRequest
 */
export interface UpdateBudgetProgramRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateBudgetProgramRequest
     */
    'description'?: string | null;
    /**
     *  IDs for existing budgets associated with this Budget Program. 
     * @type {Array<string>}
     * @memberof UpdateBudgetProgramRequest
     */
    'existing_budget_ids'?: Array<string> | null;
    /**
     *  The Blueprints to update the budget program with. Blueprints without an ID are treated as new blueprints to be created. Blueprints that exist currently on the Budget Program, but are missing from the input, will be deleted. 
     * @type {Array<UpdateBudgetBlueprintRequest>}
     * @memberof UpdateBudgetProgramRequest
     */
    'budget_blueprints'?: Array<UpdateBudgetBlueprintRequest> | null;
    /**
     * 
     * @type {CreateBudgetProgramRequestEmployeeFilter}
     * @memberof UpdateBudgetProgramRequest
     */
    'employee_filter'?: CreateBudgetProgramRequestEmployeeFilter;
    /**
     * 
     * @type {string}
     * @memberof UpdateBudgetProgramRequest
     */
    'name'?: string | null;
}

