/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BudgetLimit } from './budget-limit';
import { LimitType } from './limit-type';
import { PeriodType } from './period-type';
import { SpendType } from './spend-type';

/**
 *  Blueprint for provisioning Budgets for a Budget Program. 
 * @export
 * @interface UpdateBudgetBlueprintRequest
 */
export interface UpdateBudgetBlueprintRequest {
    /**
     *  Description of what the Budget is used for. 
     * @type {string}
     * @memberof UpdateBudgetBlueprintRequest
     */
    'description'?: string | null;
    /**
     *  ID of budget blueprint to update, omit if adding new budget blueprint to budget program. 
     * @type {string}
     * @memberof UpdateBudgetBlueprintRequest
     */
    'id'?: string | null;
    /**
     *  Name for the Budget. 
     * @type {string}
     * @memberof UpdateBudgetBlueprintRequest
     */
    'name'?: string | null;
    /**
     *  ID of parent Budget. 
     * @type {string}
     * @memberof UpdateBudgetBlueprintRequest
     */
    'parent_budget_id'?: string | null;
    /**
     *  User IDs of the owners of the Budget. 
     * @type {Array<string>}
     * @memberof UpdateBudgetBlueprintRequest
     */
    'owner_user_ids'?: Array<string> | null;
    /**
     * 
     * @type {PeriodType}
     * @memberof UpdateBudgetBlueprintRequest
     */
    'period_type'?: PeriodType;
    /**
     *  The UTC date when the Budget should start counting. 
     * @type {string}
     * @memberof UpdateBudgetBlueprintRequest
     */
    'start_date'?: string | null;
    /**
     *  The UTC date when the Budget should stop counting. 
     * @type {string}
     * @memberof UpdateBudgetBlueprintRequest
     */
    'end_date'?: string | null;
    /**
     * 
     * @type {BudgetLimit}
     * @memberof UpdateBudgetBlueprintRequest
     */
    'limit'?: BudgetLimit;
    /**
     * 
     * @type {LimitType}
     * @memberof UpdateBudgetBlueprintRequest
     */
    'limit_type'?: LimitType;
    /**
     * 
     * @type {SpendType}
     * @memberof UpdateBudgetBlueprintRequest
     */
    'spend_type'?: SpendType;
}

