/*
Budgets API


The budgets API lets you manage your Brex budgets.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BudgetLimit } from './budget-limit';
import { BudgetLimitVisibilityType } from './budget-limit-visibility-type';
import { LimitType } from './limit-type';
import { SpendType } from './spend-type';

/**
 * 
 * @export
 * @interface UpdateBudgetRequest
 */
export interface UpdateBudgetRequest {
    /**
     *  Description of what the Budget is used for. 
     * @type {string}
     * @memberof UpdateBudgetRequest
     */
    'description'?: string | null;
    /**
     *  Name for the Budget. 
     * @type {string}
     * @memberof UpdateBudgetRequest
     */
    'name'?: string | null;
    /**
     *  User IDs of the owners of the Budget. 
     * @type {Array<string>}
     * @memberof UpdateBudgetRequest
     */
    'owner_user_ids'?: Array<string> | null;
    /**
     *  User IDs of the members of the Budget. 
     * @type {Array<string>}
     * @memberof UpdateBudgetRequest
     */
    'member_user_ids'?: Array<string> | null;
    /**
     * 
     * @type {BudgetLimit}
     * @memberof UpdateBudgetRequest
     */
    'limit'?: BudgetLimit;
    /**
     * 
     * @type {LimitType}
     * @memberof UpdateBudgetRequest
     */
    'limit_type'?: LimitType;
    /**
     * 
     * @type {SpendType}
     * @memberof UpdateBudgetRequest
     */
    'spend_type'?: SpendType;
    /**
     *  The UTC date when the Budget should start counting. 
     * @type {string}
     * @memberof UpdateBudgetRequest
     */
    'start_date'?: string | null;
    /**
     *  The UTC date when the Budget should stop counting. 
     * @type {string}
     * @memberof UpdateBudgetRequest
     */
    'end_date'?: string | null;
    /**
     * 
     * @type {BudgetLimitVisibilityType}
     * @memberof UpdateBudgetRequest
     */
    'limit_visibility'?: BudgetLimitVisibilityType;
}

